### PR TITLE
Fix optional param converter

### PR DESCRIPTION
**Pull request by LuSimeon**
PommBundle ParamConverter does not allow optional parameters.

``` php
/**
* @Route("/user/add/")
* @ParamConverter("user")
*/
public function addAction(User $user = null)
{}
```

### CODE REVIEW

**Comment by sanpii** [comment]
Can you add a behat test for this feature?

**Comment by chanmix51** [comment]
I am not sure I get the point of this patch. What does it stand for ?

**Comment by sanpii** [comment]
@chanmix51 if you define two routes with the same end-point:

```yml
get_default:
    path: /get
    defaults: { _controller: index_controller:getAction }
    methods: [GET]

get:
    path: /get/{name}
    defaults: { _controller: index_controller:getAction }
    methods: [GET]
```

```php
    public function getAction(Config $config = null)
    {
    }
```

Currently, makes a 500 error:

```
Missing primary key element 'name'
500 Internal Server Error - LogicException
```

**Comment by LuSimeon** [comment]
@sanpii I added behat test to valid new comportment of the param converter.
Commits contains a param converter bugfix too.

**Comment by sanpii** [comment]
Merged, thank you :smiley:

**Comment by baptistedonaux** [comment]
Oh yeah ! Thanks

**Pull request closed without merging**
