### PR TITLE
split extension to work on container external definition in a compiler pass

### PR DESCRIPTION
**Pull request by lunika**
This PR refers to #76 
I split the extension to work only on configuration in it and with external service definition in a compiler pass where is I think the best place to manipulate external definitions.

WDYT about this modification ?

### CODE REVIEW

**Comment by lunika** [comment]
@sanpii can you take a look ? Should be great to release version 2.3.1 soon with this bug fix.

**Comment by sanpii** [comment]
Merged, thank you.

**Comment by lunika** [comment]
Great, thanks. How did you merged it ?

**Comment by sanpii** [comment]
> How did you merged it ?

Via the command line (helped by a [little script](https://github.com/sanpii/git-pr/)). I always rebase the PR to keep a clean history graph, github doesn’t like that.

**Pull request closed without merging**
