### PR TITLE
Define default SessionBuilder class in the config

### LINKED ISSUE #38: BaseGenerator::__construct() must be an instance of PommProject\ModelManager\Session
I'm trying to install the PommBundle (latest version). 

Here is my config:
```yaml
pomm:
    configuration:
        redshift:
            dsn: 'pgsql://%redshift.username%:%redshift.password%@%redshift.host%:5439/%redshift.database%'
    logger:
        service: '@logger'
```

When running the following command I get an exception:

```
php console pomm:generate:relation-all -d src/ -a 'PublicationBundle\Model' redshift client
```

```
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to PommProject\ModelManager\Generator\BaseGenerator::__construct() must be an instance of PommProject\ModelManager\Session, 
  instance of PommProject\Foundation\Session given, called in vendor/pomm-project/cli/sources/lib/Command/GenerateForRelation.php on line 76 and defined
```

Is there something to configure for the `class:session_builder` ? This config is in the Configuration class, but I don't find the expected value.

### PR DESCRIPTION
**Pull request by GromNaN**
Fix #38

Same as the Zend Module. https://github.com/pomm-project/PommModule/blob/183d0c17bcb16e7c7b25ac0fdef27f16e6dabf92/src/Service/AbstractServiceFactory.php#L44

### CODE REVIEW

**Comment by chanmix51** [comment]
Sounds great to me :+1:

**Comment by sanpii** [comment]
@chanmix51 can you confirm always load Model and ModelLayer poolers has no significant overload?

**Comment by chanmix51** [comment]
Yes I do confirm. Registering the poolers is ok.

**Comment by webaaz** [comment]
good :) Thanks @GromNaN

**Pull request merged**
